/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreationsRouteImport } from './routes/_app.creations'
import { Route as AppCreationsIndexRouteImport } from './routes/_app.creations.index'
import { Route as AppCreationsCreationIdRouteImport } from './routes/_app.creations.$creationId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreationsRoute = AppCreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => AppRoute,
} as any)
const AppCreationsIndexRoute = AppCreationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCreationsRoute,
} as any)
const AppCreationsCreationIdRoute = AppCreationsCreationIdRouteImport.update({
  id: '/$creationId',
  path: '/$creationId',
  getParentRoute: () => AppCreationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creations': typeof AppCreationsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/creations/$creationId': typeof AppCreationsCreationIdRoute
  '/creations/': typeof AppCreationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/creations/$creationId': typeof AppCreationsCreationIdRoute
  '/creations': typeof AppCreationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/creations': typeof AppCreationsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/creations/$creationId': typeof AppCreationsCreationIdRoute
  '/_app/creations/': typeof AppCreationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creations'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/creations/$creationId'
    | '/creations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/creations/$creationId'
    | '/creations'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/creations'
    | '/_app/dashboard'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/creations/$creationId'
    | '/_app/creations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creations': {
      id: '/_app/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof AppCreationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creations/': {
      id: '/_app/creations/'
      path: '/'
      fullPath: '/creations/'
      preLoaderRoute: typeof AppCreationsIndexRouteImport
      parentRoute: typeof AppCreationsRoute
    }
    '/_app/creations/$creationId': {
      id: '/_app/creations/$creationId'
      path: '/$creationId'
      fullPath: '/creations/$creationId'
      preLoaderRoute: typeof AppCreationsCreationIdRouteImport
      parentRoute: typeof AppCreationsRoute
    }
  }
}

interface AppCreationsRouteChildren {
  AppCreationsCreationIdRoute: typeof AppCreationsCreationIdRoute
  AppCreationsIndexRoute: typeof AppCreationsIndexRoute
}

const AppCreationsRouteChildren: AppCreationsRouteChildren = {
  AppCreationsCreationIdRoute: AppCreationsCreationIdRoute,
  AppCreationsIndexRoute: AppCreationsIndexRoute,
}

const AppCreationsRouteWithChildren = AppCreationsRoute._addFileChildren(
  AppCreationsRouteChildren,
)

interface AppRouteChildren {
  AppCreationsRoute: typeof AppCreationsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreationsRoute: AppCreationsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
